
# datasource

spring.datasource.url = jdbc:mysql://localhost:3306/nasiona?useSSL=false
spring.datasource.username = clroot
spring.datasource.password = coderslab

# hibernate JPA

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

