

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nasiona?useSSL=false
    username: clroot
    password: coderslab
    sql-script-encoding: utf-8
    hikari:
      data-source-properties.useUnicode: true
      data-source-properties.characterEncoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    locale: pl_PL
  http:
    encoding:
      charset: UTF-8
      enabled: true

server:
  port: 8080

