Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nasiona?useSSL=false
    username: clroot
    password: coderslab

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    view:
      suffix: .html