

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nasiona?useSSL=false
    username: clroot
    password: coderslab

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    locale: pl_PL

server:
  port: 8080
